// <auto-generated />
namespace NickAndArtie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class slidehsows : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(slidehsows));
        
        string IMigrationMetadata.Id
        {
            get { return "201208300127338_slidehsows"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
