// <auto-generated />
namespace NickAndArtie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cantrememerb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cantrememerb));
        
        string IMigrationMetadata.Id
        {
            get { return "201208300227295_cantrememerb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
