// <auto-generated />
namespace NickAndArtie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostIsActive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostIsActive));
        
        string IMigrationMetadata.Id
        {
            get { return "201208251551509_PostIsActive"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
